UKHomeOffice/asl-resolver

lib/api.js, lib/resolvers/index.js, lib/resolvers/place.js, package-lock.json, package.json
Where an amendment change is received for a place model, merge the changes back into the database record, or create a new record as appropriate.
=> Resolve `place` actions into database

lib/keycloak/index.js
This action is no longer created by keycloak, so we don't need to remove it.
=> Remove code to remove password reset required action

lib/resolvers/index.js, lib/resolvers/profile.js, test/resolvers/profile.js
* This currently only handles profile updates
=> Added update profile resolver

lib/resolvers/invitation.js, lib/resolvers/pil.js, lib/resolvers/place.js, lib/resolvers/profile.js, lib/resolvers/training-module.js, lib/worker.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/invitation.js, test/resolvers/pil.js, test/resolvers/place.js
This requires https://github.com/UKHomeOffice/asl-schema/pull/89 to be merged and bumped
=> add message to changelog once successfully resolved

lib/resolvers/pil.js, lib/resolvers/place.js, lib/resolvers/training-module.js
* returning('*') doesn't work for soft deleted models, lookup and return the soft deleted model then add to changelog
=> Return soft deleted model on delete

lib/resolvers/base-resolver.js, lib/resolvers/certificate.js, lib/resolvers/exemption.js, lib/resolvers/index.js, lib/resolvers/profile.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/pil.js
Updated to remove some of the duplicated code for simple models
=> Added resolvers for exemptions and certificates

lib/changelog/index.js, lib/resolvers/base-resolver.js, lib/resolvers/certificate.js, lib/resolvers/exemption.js, lib/resolvers/invitation.js, lib/resolvers/pil.js, lib/resolvers/place.js, lib/resolvers/profile.js, lib/worker.js, package-lock.json, package.json
This ensures that if any one database update fails then any previous updates will be reverted.
~Needs https://github.com/UKHomeOffice/asl-schema/pull/111 to un-WIP.~
=> Use transactions for database queries

lib/resolvers/index.js, lib/resolvers/role.js, package-lock.json, package.json
I've opened a ticket to make the roles resolver idempotent and not add multiple records corresponding to the same role-person-establishment tuple.
=> Add a resolver for roles

lib/resolvers/role.js
If adding the same person-role-establishment as one that already exists don't create multiple instances.
=> Ensure named roles are unique

lib/resolvers/project-version.js
New projects have data: `null` and did not save input.
=> Don't try and patch null data

lib/tasks/expire.js
We don't want to expire revoked licences.
=> Only expire active licences

lib/resolvers/project-version.js
The id isn't a property of the data, so needs to be set separately.
=> Add ids to the changelog data

lib/resolvers/project.js
Updated project resolver to update ppl holder - draft projects are insta-resolved and latest draft is writtin to directly, granted PPLs are forked with the statuys preserved
=> Amend PPL holder

.dockerignore, package-lock.json
Per item HOFF-221-7-1 of the ITHC report. Remove the ability to run inject script on deployed pod. Also remove tests because obviously.
=> Ignore test and bin directories

lib/resolvers/project.js, test/resolvers/project.js
* added ability to provide version data when creating a new project
* added tests
=> Feature - upload ppl

lib/resolvers/project.js, test/resolvers/project.js
* lookup most recent granted version
* dont update expiry date if duration not changed
* added tests
=> Bugfix - expiry dates

index.js, lib/resolvers/profile.js
Updates the profile id of anything that was associated with the old profile to the new profile id.
=> Resolve merge actions on Profile model

lib/resolvers/project.js, test/resolvers/project.js
If duration is missing or invalid, set expiry date to be 5 years from date of granting
=> Expiry date bugfix

lib/tasks/expire.js, lib/utils/scheduler.js, lib/worker.js, test/tasks/expire.js
`.update()` validates the passed object against the json schema so it always fails (missing required props).
Even with `.patch()` it does not seem to execute the queries unless we use `await`.
=> Use patch instead of update, queries are async

lib/resolvers/project-version.js
* restrospeciveAssessment will be a boolean going forward - use isUndefined to ascertain whether to update the value, rather than a falsy check
=> Feature - refactor retrospective assessment

lib/resolvers/project-version.js
Reverts UKHomeOffice/asl-resolver#104
We're not confident of this being b/c
=> Revert "Feature - refactor retrospective assessment"

lib/resolvers/project-version.js
Reverts UKHomeOffice/asl-resolver#105
=> Revert "Revert "Feature - refactor retrospective assessment""

lib/resolvers/place.js, lib/resolvers/role.js, test/resolvers/place.js, test/resolvers/role.js
Any changes to the roles or the places within an establishment are also counted as changes to the establishment licence itself. Touch the `updated_at` value of the owning establishment when a role or place model resolves with a change.
=> Update the "updated_at" on an establishment if a dependent model changes

package-lock.json, package.json, test/resolvers/establishment.js
Waiting on schema bump https://github.com/UKHomeOffice/asl-schema/pull/221
=> Add a test for establishment create

README.md, config.js, index.js, lib/emailer/index.js, lib/resolvers/profile.js, lib/s3/index.js, lib/tasks/expire.js, lib/utils/logger.js, lib/worker.js, package-lock.json, package.json, test/resolvers/profile.js, test/tasks/expire.js
* Adds a winston instance to support customisable log levels and rich json logs. This improves log management in Kibana as it makes the logs easier (possible) to query. Particularly for error-level logs.
* Adds a statsd event to errors so we can alert on resolver errors, which are probably the most critical to avoid anywhere in our service as they result in 30 second timeouts and no possible client-side handling.
=> Improve message logging on resolver

lib/resolvers/role.js, test/resolvers/role.js
* A holc is not a named role, dont update est if changed
=> Bugfix - Dont touch est on holc change

lib/emailer/index.js, lib/resolvers/invitation.js, package-lock.json, package.json, test/resolvers/invitation.js
* Added cancel action which sets token to null
* Added resend action which resets token and resends email
* Added delete action which soft deletes the invitation
WIP as needs https://github.com/UKHomeOffice/asl-schema/pull/229
=> Feature - invitation actions

lib/resolvers/project.js, package-lock.json, package.json, test/resolvers/project.js
The same task should be able to be sent twice without throwing an error.
=> Allow grant actions on already granted project versions to resolve

lib/changelog/index.js, lib/worker.js
* Added logError function to changelog which writes the error message
* Updated changelog implementation to export a function for standard logging
=> Feature - write errors to changelog

lib/resolvers/project.js, package-lock.json, package.json, test/resolvers/project.js
* if an asru user initiates fork, mark the asruVersion flag on the version to true
=> Fetaure - update asruVersion flag on fork

lib/resolvers/establishment.js, package-lock.json, package.json
* update billing property from body on update-billing
=> Feature - resolve update-billing

.drone.yml, README.md, lib/resolvers/project.js, package-lock.json, package.json, test/resolvers/project.js
* Added transfer action to project resolver
* check version is submitted
* create new project in transfer to est
* create new granted version in new project, removing transfer flag
* update old project status to transferred
~needs https://github.com/UKHomeOffice/asl-schema/pull/264~
=> Feature - PPL transfer

lib/resolvers/pil.js, test/resolvers/pil.js
* Added resolver for pil review - adds 5 years to review date
=> Feature - PIL review

lib/resolvers/project.js, lib/utils/generate-licence-number.js, lib/utils/index.js, lib/utils/normalise-project-version.js, package-lock.json, package.json, test/resolvers/project.js
If uploading a .ppl file some of the species details sections might be missing id properties if they were created before a certain point.
Make sure these get set when we import the .ppl file
=> Set id properties on protocol species details on import

lib/resolvers/index.js, lib/resolvers/project-profile.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/project-profile.js
* added resolver for creating and deleting project profiles
~WIP until https://github.com/UKHomeOffice/asl-schema/pull/295~
=> Feature - Project Profiles

lib/worker.js
Send messages processed and processing time stas to statsd.
Log completed messages and processing time to logs.
=> Add performance metrics

lib/resolvers/profile.js, lib/worker.js, package-lock.json, package.json, test/helpers/emailer.js, test/resolvers/profile.js
This ensures it actually writes the update to the changelog rather than an empty model state.
Also ensure keycloak errors are written to logs.
=> Return profile from email update resolver

lib/resolvers/place.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/place.js
~Needs https://github.com/UKHomeOffice/asl-schema/pull/313~
=> Place roles

README.md, config.js, lib/s3/index.js
Dependent on https://github.com/UKHomeOffice/asl-deployments/pull/434
=> Handle encrypted messages sent by workflow

lib/resolvers/project-version.js, package-lock.json, package.json
Replaced deep-diff with jsondiffpatch which handles updating objects by id, rather than sending a mahoosive diff payload for protocol reordering
=> Bugfix - large diffs

lib/resolvers/project-version.js, lib/resolvers/project.js, lib/utils/index.js, lib/utils/retrospective-assessment.js, package-lock.json, package.json, test/resolvers/project.js
* added raDate to project if applic on grant, 6 months after expiry
* added ra props to version on grant
* set raDate as 6 months after revocation on revoke
=> Feature - store RA in data

lib/resolvers/index.js, lib/resolvers/training-course.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/training-course.js
* added training course resolver, proxies base resolver for now
* bumped schema
=> Feature - training course

lib/resolvers/index.js, lib/resolvers/training-pil.js, package-lock.json, package.json, test/resolvers/training-pil.js
* Added training pil resolver
* create profile if not exists
* update dob if missing
* create inactive training pil
* grant training pil
* associate pil holder with est
* generate pilLicenceNo if missing
* revoke trainingPil
=> Feature - training pil resolver

tasks/expire.js
* Updated the expiry task to include training pils
=> Feature - expire training pils

lib/resolvers/project-version.js, lib/resolvers/project.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/project-version.js, test/resolvers/project.js
* Added step to version patch to update additional availability
* check all estIds, add new ones, remove drafts, update status of active links
=> Feature - additional availability

lib/resolvers/project-version.js, lib/resolvers/project.js, test/resolvers/project-version.js, test/resolvers/project.js
* Remove all establishments if other-establishments is set to false (or not set)
=> Bugfix - remove all additional availability

lib/resolvers/project.js, package-lock.json, package.json
* mark issueDate and revokedDate on grant
=> Feature - issue and revoked dates AA

lib/utils/normalise-project-version.js, test/resolvers/project.js
* when importing a ppl, strip establishments and transfer info
=> Bugfix - strip aa and transfer info on import

lib/emailer/index.js, lib/jwt/index.js, lib/resolvers/profile.js, package-lock.json, package.json, test/resolvers/invitation.js, test/resolvers/profile.js
And set flag on profile to mark email as verified.
=> Send email verification messages

lib/resolvers/project-version.js, lib/resolvers/project.js, lib/utils/extract-species.js, lib/utils/index.js, package-lock.json, package.json, test/resolvers/project-version.js, test/resolvers/project.js
* Extract species from project version on grant, and on draft submission
=> Feature - project species

lib/resolvers/profile.js, package-lock.json, package.json, test/resolvers/profile.js
* Added profile action to update last login
* bumped schema
=> Feature - update last login

lib/resolvers/index.js, lib/resolvers/project.js, lib/resolvers/retrospective-assessment.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/project.js, test/resolvers/retrospective-assessment.js
* Added fork, submit-ra and grant-ra actions to project resolver
* Added ra resolver to patch
=> Feature - RA

lib/resolvers/email-preferences.js, lib/resolvers/index.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/email-preferences.js
~needs https://github.com/UKHomeOffice/asl-schema/pull/437~
=> Resolve email preferences for a profile

lib/resolvers/project-version.js, test/resolvers/project-version.js
* Only update raCompulsory on patch if the licence status is inactive
=> Feature - dont update raCompulsory for granted liences

lib/resolvers/project.js, test/resolvers/project.js
* if an ra is granted, and a grant task resolves, noop
=> Bugfix - noop granted ra

lib/resolvers/establishment.js, package-lock.json, package.json
* Added CJSM patch to est resolver
=> Feature - CJSM email

lib/resolvers/project.js, test/resolvers/project.js
If a PPL holder on an active PPL is changed then it needs to update the amended date on the project record.
=> Update project amended date when changing PPL holder

lib/resolvers/project.js, test/resolvers/project.js
Need a licence holder on the initial version as well...
=> Set version LH on project create

lib/resolvers/base-resolver.js, lib/resolvers/index.js, lib/resolvers/procedure.js, lib/resolvers/rop.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/procedure.js, test/resolvers/rop.js
* Added resolvers for rops and procedures
* bumped schema
=> Feature - ROPS

lib/resolvers/export.js, lib/resolvers/index.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/export.js
Allows creation of export records to be processed by the data exports worker
=> Add resolver for export model

lib/resolvers/place.js, lib/resolvers/project.js
Newer versions of knex throw errors on attempting to insert an empty array.
=> never attempt to insert empty arrays

lib/resolvers/project-profile.js, test/helpers/db.js
* Added update resolver to projProfile
* bumped schema with role field
=> Feature - collab perms

lib/resolvers/project.js, test/resolvers/project.js
* Updated project change licence holder resolver to pick fields from data rather than meta.
* left meta for fallback
=> Feature - PPL awerb

lib/resolvers/establishment.js, package-lock.json, package.json
This allows ASRU business support to see who has recently updated the contact information for their billing and who might have out-of-date information.
=> Add an updatedAt flag to billing contact data when updating

lib/resolvers/establishment.js, lib/resolvers/index.js, lib/resolvers/pil.js, lib/resolvers/project-version.js, lib/resolvers/project.js, lib/resolvers/reminder.js, lib/utils/extract-reminders.js, lib/utils/index.js, package-lock.json, package.json, test/helpers/db.js, test/resolvers/establishment.js, test/resolvers/pil.js, test/resolvers/project-version.js, test/resolvers/project.js, test/resolvers/reminder.js
Requires:
- https://github.com/UKHomeOffice/asl-schema/pull/558
=> Save reminders for PPL/PIL/PEL conditions

lib/resolvers/project.js, package-lock.json, package.json
Needs: 
* https://github.com/UKHomeOffice/asl-schema/pull/564
=> Set refused_date when project is refused

lib/resolvers/profile.js, package-lock.json, package.json
Needs:
- https://github.com/UKHomeOffice/asl-schema/pull/577
=> Log profile merges so we can flag them

.auditrc.json, .drone-1.0.yml, lib/resolvers/establishment.js, lib/resolvers/place.js, lib/resolvers/role.js, lib/utils/update-conditions.js, package-lock.json, package.json, test/resolvers/establishment.js, test/resolvers/place.js, test/resolvers/role.js
- Update task resolvers to push reminder and establishment data to db
=> Allow PEL conditions to be changed during amendment tasks

.drone-1.0.yml, .npmrc, Dockerfile, lib/utils/extract-species.js, lib/utils/retrospective-assessment.js, package-lock.json, package.json
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4304
Lenny's creds no longer work for publishing to artifactory npm. This replaces his credentials with one provided by ACP.
=> Update npmrc to use new artifactory token

.eslintrc.yml, .prettierrc, lib/resolvers/project.js, package-lock.json, package.json, test/resolvers/project.js
* If hbaToken present add to projectVersion on grant, if not set to null
* Bumped schema to 10.17.0
=> Feture - add hbaToken to project version on grant if present

tasks/reset-billing.js
https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4475
To run locally - connecting to the database started by asl-conductor:
```
DATABASE_NAME=asl \
DATABASE_USERNAME=postgres \
DATABASE_PASSWORD=test-password \
npm run task -- ./tasks/reset-billing.js
```
=> Add task to clear billing POs/other info from establishments
