UKHomeOffice/asl-resolver

lib/worker.js
The message body is a JSON encoded string, not an object, so it needs to be parsed before trying to work with it.
=> Parse JSON on message bodies

index.js
Queue should attempt to reconnect periodically instead of permanently crashing is SQS is not available.
=> Prevent resolver from crashing if SQS queue is not present

config.js
Make sure that if database username isn't explicitly set then it defaults to the most useful value, which is the username used by the conductor.
=> Set default database username

lib/worker.js
At the moment failed messages stay on the queue and are periodically re-processed. This is bad.
It means that the client will have already erroed out, and will likely attempt to resend the same or similar message. This will result in duplicate messages on the queue, and so in all likelihood, more errors.
This in turn makes a mess of the logs, and can potentially have unexpected side effects if for whatever reason a previously failed message becomes deliverable.
The best thing to do is to discard failed messages (by treating them as processed) but by virtue of not having written to the changelog, the client will throw.
tl;dr - it's better to know the thing hasn't been done if it errors, than for it to maybe happen at some unknown point in the future.
=> Always resolve messages

lib/resolvers/profile.js
If a person logs in with no profile, but a profile exists with the same email as their login then associate that profile rather than trying to create a new one (which will fail due to uniqueness constraints on email addresses)
=> Associate login emails with profile emails

lib/resolvers/profile.js
The transaction parameter wasn't being passed through to the base resolver when processing profile changes. This causes sporadic errors in database connections.
=> Use transactions for profile updates

lib/resolvers/project-version.js
If a brand new project is created then the `data` field is null, and trying to read the title throws an error.
Instead use `lodash.get` to read the title so it doesn't fail.
=> Handle first patch of a new project

lib/resolvers/pil.js
Previously a user would add procedures to an inactive PIL then apply for that PIL to be granted - this does not scale to PIL amends as the data cannot be mutated on an active PIL. Instead always update data on a resolved grant action
=> pil should update data on a grant action

lib/utils/scheduler.js
The check that `lastCall` exists in the task runner means it never actually runs because it's initialised as undefined.
=> Actually run scheduled tasks

lib/tasks/expire.js
Projects with a status of `revoked` shouldn't be changed to `expired`.
=> Only expire active projects

lib/resolvers/project-version.js
They get very big very quickly when they're being saved every few seconds.
Instead save only the patch data for patch updates.
=> Don't save complete project versions to changelog

lib/resolvers/pil.js, lib/worker.js
If a PIL application makes it through with `species: []` then revert it to `null`.
Also log the actual message when one fails.
=> Handle empty species on PILs

lib/resolvers/project.js
Add an action to the top level project that fetches the most recent draft version and marks it as submitted. Part of a larger refactor of project submission to perform all necessary actions on a single API request.
Leaves the existing project-version submit action in place for backwards compatibility, but that should be removed eventually.
=> Add an action on a project to submit draft

lib/resolvers/project.js
We _think_ that the call to `moment.add` is modifying the `issueDate` as well. By extracting the `issueDate` as a string before modifying then we can prevent this.
=> Avoid manipulating issue date when updating projects

lib/resolvers/place.js, test/resolvers/place.js
Place creation is failing when no NACWO is defined because we try to do a database lookup with an empty id.
Check that the profile id of the NACWO is defined before trying to find an associated role record.
=> Fix place creation with no NACWO

lib/resolvers/place.js
The validation requiring a NACWO was removed in the UI, which now means that approved area additions are coming in with no NACWO assigned. They currently fail when being processed by ASRU.
=> Allow place creation with no NACWO

lib/resolvers/project-version.js
Storing the complete patch object on every project version write is using up _a lot_ of data for data we dont actually need.
Specifically the changelog table is currently 15gb of data.
=> Don't save patch data to changelog on project edits

lib/worker.js
Apparently the `body` property causes some issues downstream with ES which is why the logs from prod are not appearing correctly.
Flatten the JSON structure to get rid of the `body`.
=> Flatten log json

lib/changelog/index.js
If the loading of the message from S3 fails then there will be no body, and so any attempt to write an error will throw another error.
=> Add a default message body in log error function

lib/resolvers/project.js, test/resolvers/project.js
This defaults the `asruVersion` property on a project vesion to false if no `meta.changedBy` is provided for backwards compatibility.
=> Handle missing changedBy value in project resolver

lib/resolvers/project.js, test/resolvers/project.js
* We want to preserve the asruVersion status for the life of an amendment, therefore only update asruVersion flag on fork if version if granted
=> Bugfix - dont update asruVersion flag unless granted

lib/worker.js
This allows the error rate metric to revert to zero and resolve error alerts.
=> Send zero error metric to sysdig on success

lib/resolvers/pil.js, test/resolvers/pil.js
This allows the issue dates and revocation dates to be correctly preserved when a PIL is revoked and re-granted several times.
=> Create new database record if re-granting a revoked PIL

lib/resolvers/project.js
Some bits of the UI rely on `version.data.protocols` being an array.
=> Store empty protocols array when creating the stub

lib/changelog/index.js
Sometimes resolver errors with an issue retrieving data from S3. In those cases the model type is undefined, and so writing the error fails because type is a required property in the changelog table.
Set a default model type of `error` when writing errors so that the error record can be inserted and workflow can detect the error immediately instead of timing out.
Also means only one error is logged, rather than an error and then another error logging the first error.
=> Set default model type when logging an error to the changelog

lib/resolvers/project-version.js, test/resolvers/project-version.js
The protocols array is defaulted to an empty array in the API layer, so the client never thinks it is adding it. That means we have to add it in the version patch resolver to ensure that the diff is being applied to the same ground state.
=> Default protocols to empty array

lib/resolvers/project-version.js
One of these was failing on prod and was impossible to debug because we have no visibility of the underlying data.
Include the patch payload in the log if an error is thrown when applying patches.
=> Include patch data on error if project-version patch fails

.nycrc.yml, package-lock.json, package.json, test/resolvers/asru-establishment.js, test/resolvers/certificate.js, test/resolvers/exemption.js, test/resolvers/permissions.js
Add a basic implementation of Istanbul/NYC to the unit tests to report on test coverage in `./lib` and fail on zero coverage.
=> Add test coverage reporting

lib/resolvers/establishment.js, lib/resolvers/pil.js, lib/resolvers/project.js, lib/utils/generate-licence-number.js, package-lock.json, package.json, test/resolvers/pil.js
* PIL licence number is now part of a profile not a pil, updated PIL resolver to set pilLicenceNumber to profile if on grant if not already set
* Updated generate-licence-number helper to take an object, with a customisable key
=> Feature - pull PIL licence number to profile

lib/resolvers/profile.js, test/resolvers/profile.js
Adds logic to copy the most relevant `pilLicenceNumber` to the target profile when two profiles are merged.
Where both profiles have a licence number then use the active PIL if it exists, or preserve the target profile's licence number otherwise.
=> Merge PIL licence numbers on profile merge

lib/resolvers/pil.js, test/resolvers/pil.js
The profile being checked for a licence number before was the user who submitted the application, not the PIL holder themselves.
This has resulted in PILs being granted with no licence number where the person submitting on the PIL holder's behalf had a PIL of their own.
=> Use correct profile when checking for PIL licence number

lib/resolvers/fee-waiver.js, package-lock.json, package.json, test/resolvers/fee-waiver.js
A waiver applies to all related PIL records for an establishment, so use the parent profile as the key and not the PIL record.
WIP until https://github.com/UKHomeOffice/asl-schema/pull/378
=> Use Profile IDs for PIL fee waivers and not PILs

lib/resolvers/profile.js
Since data encoded in jwt tokens can be extracted without the signing secret including the entire profile in the token could potentially leak personal data.
=> Only include id and email in verification token

lib/utils/retrospective-assessment.js, test/resolvers/project-version.js
A severe protocol which has been deleted should not trigger RA - it currently does.
=> Disregard deleted protocols when calculating RA

lib/resolvers/project.js, test/resolvers/project.js
This was being dropped when forking projects, resulting in the RA condition going missing if an application or amendment was resubmitted without changes.
=> Copy raCompulsory flag on fork

lib/resolvers/project.js, test/resolvers/project.js
The desired behaviour for ASRU submitting retrospective assessments is for them to resolve immediately without needing to be reviewed by an inspector or licensing officer.
This means they need to bypass the check the the most recent version is submitted in order to grant, because at this point the version is `draft`.
=> Allow ASRU user to directly grant an RA

lib/resolvers/project.js, test/resolvers/project.js
Currently when a PPL with additional establishments is transferred the new relations are not created at the target establishment.
This means that the transferred PPL ceases to be available at it's additional establishments.
=> Create additional availability associations on transferred PPLs

lib/resolvers/profile.js
Only need the bare minimum not to save the entire profile. This will reduce the amount of disk space used in the longer term.
=> Reduce amount of data stored in last login changelog

lib/resolvers/profile.js
The licence holder id is stored on project versions now as well as projects, so when profiles are merged and the projects are updated we need to also move the versions.
=> Update project versions on profile merge

lib/resolvers/project.js, test/resolvers/project.js
Had a question from ASRU about a revocation request for a project that had expired while the task was open and what the effects of resolving the task would be.
As a result, make it not possible to revoke projects that are already expired.
=> Don't allow revocation of expired projects

lib/resolvers/place.js, lib/resolvers/role.js, test/resolvers/place.js, test/resolvers/role.js
Two issues, each addressed in it's own commit:
1. Places were not being correctly disassociated from NVS and NACWOs when those roles were removed - update the code to correctly remove the relations.
2. In flight place amendments with NVS and NACWOs that were removed while the task was open could not be resolved because they tried to re-add the role, which did not exist. Add a filter to the `newRoles` so that only roles which exist on the establishment at the time of resolution are included.
=> Fix place role assignments

lib/resolvers/project.js, test/resolvers/project.js
If an applicant has selected "No" for their PPL having additional establishments then remove any nested data for the establishments at the point of granting.
This prevents any issues if a PPL holder has establishment affiliations removed but the association from the project being partially revived if additional establishments later switched to "Yes".
Also ensure that the same process is included in a transfer resolution as transfers and amendments are equivalent.
=> Clean project additional establishments on grant

lib/resolvers/project.js
The addition of the training data needs to be done at the point of submission for endorsement so that it is available to the admin user reviewing the project for endorsement.
To be able to do this separately from the status update of the version it needs to be split into a separate action from `submit-draft` which is called only after endorsement.
=> Split sync of training and submission to ASRU

index.js, lib/worker.js
The major version bump of `sqs-consumer` changes the module structure and method signature slightly - most significantly to use promises/async-await instead of callbacks.
=> Update sqs-consumer implementation

lib/resolvers/project-version.js, test/resolvers/project-version.js
When a draft PPL has an additional establishment removed it doesn't delete it from the version data, only sets a deleted flag.
However it should be removed from the relation table so it doesn't appear as an additional establishment on project landing pages, or ask for AWERB details when submitting.
Integration test at https://github.com/UKHomeOffice/asl-deployments/pull/1308
=> Remove deleted additional establishments from draft PPLs

lib/utils/extract-reminders.js
This is throwing errors in production due to `condition.reminders[conditionKey]` being undefined. If that is the case allow the `reduce` to continue instead of throwing errors.
=> Handle case where reminders is undefined

lib/resolvers/establishment.js, package-lock.json, package.json, test/resolvers/establishment.js
This is causing the licence documents to have a "last amended" timestamp that does not correspond to any amendment.
~WIP pending https://github.com/UKHomeOffice/asl-schema/pull/565~
=> Preserve PEL updated at timestamp when editing billing data

lib/resolvers/project-version.js
Fix for [ASL-4062](https://collaboration.homeoffice.gov.uk/jira/browse/ASL-4062)
Compares the reminders in the submission to the reminders in the database for each condition
If a reminder has been removed (ie in the database but not in the submission) add the deleted flag to the reminder
=> Add deleted flag to reminders when they are removed

lib/resolvers/role.js, test/resolvers/role.js
Have used a new action type that accepts the roles being replaced in the data `replaceRoles`, that way if there are any other roles that need similar functionality in the future the additional data can be passed in.
=> ASL-4052 - Add replace action for role
